; Lubla(DS#DX2) (c)Compile 用
; メインルーチン

	cseg
	org	06000h

stack:	equ	0f300h		; スタックエリア

; メインループ

main:
	di
	im	1
	ld	sp,stack
	call	init
	ei

loop:
	in	a,(02h)		; キー入力待ち
	or	a
	jr	z,loop

	cp	01h
	jr	nz,stop

; play
	in	a,(05h)
	cp	01
	call	z,00F97h	; Stop

	in	a,(03h)		; Code No.

	push	af
	di
	in	a, (04h)
	out	(03h), a
	ld	a,(fm_flag)
	call	0EC7h
	ei
	pop	af

	call	00FD3h		; Play

	jr	play_end

stop:
	di
	call	00F97h		; Stop
	ei

play_end:
	xor	a		; hoot status変更
	out	(02h),a
	jr	loop

init:
; Regist entry
	ld	a, 0c3h
	ld	(0038h), a

	ld	a, 0c9h
	ld	(0100h), a

	ld	hl, irq
	ld	(0039h), hl

; Init
	in	a, (07h)
	cp	00
	jr	z, dev_psg
	ld	a, 080h
	jr	init_end
dev_psg:
	xor	a
init_end:
	ld	(fm_flag),a
	ret

fm_flag:
	db	00h

irq:
	push	hl
	push	de
	push	bc
	push	af
	exx
	ex	af,af'
	push	hl
	push	de
	push	bc
	push	af
	push	iy
	push	ix
	call	00100h
	pop	ix
	pop	iy
	pop	af
	pop	bc
	pop	de
	pop	hl
	ex	af,af'
	exx
	pop	af
	pop	bc
	pop	de
	pop	hl
	ei
	ret
