; DS#0 (c)Compile 用
; メインルーチン

	cseg
	org	06000h

stack:	equ	0f000h		; スタックエリア

; メインループ

main:
	di
	im	1
	ld	sp,stack
	call	init
	ei

loop:
	in	a,(02h)		; キー入力待ち
	or	a
	jr	z,loop

	cp	01h
	jr	nz,stop

	call	025FCh		; Stop

	ld	hl,07228h	; table
	in	a,(04h)		; flag
	cp	01h
	jr	nz,play
	ld	hl,0443Bh	; table

play:
	ld	a, 03h
	call	02560h

	in	a,(03h)		; Code No.

	di
	call	0012Dh		; Play
	ei

	jr	play_end

stop:
	di
	call	025FCh		; Stop
	ei

play_end:
	xor	a		; hoot status変更
	out	(02h),a
	jr	loop

init:
; Regist entry
	ld	a, 0c3h
	ld	(0038h), a
	ld	(001Ch), a

	ld	hl, timer
	ld	(0039h), hl

	ld	hl, calslt
	ld	(001Dh), hl

; Init
	in	a,(07h)		; デバイス取得(01:opll)
	cp	0
	jr	z, dev_psg
	cp	2
	jr	z, dev_msxa
	ld	a, 80h
	jp	initdrv
dev_msxa:
	ld	a, 0A0h
	jp	initdrv
dev_psg:
	ld	a, 00h
initdrv:
	call	02560h

	ld	a, 01h
	call	02560h
	ret

calslt:
	ret
;	jp	(ix)

timer:
	push	hl
	push	de
	push	bc
	push	af
	exx
	ex	af,af'
	push	hl
	push	de
	push	bc
	push	af
	push	iy
	push	ix
	call	01B01H
	pop	ix
	pop	iy
	pop	af
	pop	bc
	pop	de
	pop	hl
	ex	af,af'
	exx
	pop	af
	pop	bc
	pop	de
	pop	hl
	ei
	ret
