; ランダーの冒険II(Disc Station #SP2) (c)1989 Compile
;
; @autor RuRuRu
; @date 2012/12/18 1st Release

	cseg
	org	00400h

stack:	equ	0f380h

main:
	di
	im	1
	ld	sp,stack
	call	init
	ei

loop:
	in	a,(02h)		; Key wait
	or	a
	jr	z,loop

	cp	01h
	jr	nz,stop

; play
	in	a,(03h)		; Code No.
	push	af

	in	a,(04h)
	cp	(loaded)
	call	nz,load_drv

	pop	af
	call	0537Dh		; Play

	jr	play_end

stop:
	call	05348h

play_end:
	xor	a		; Change hoot status
	out	(02h),a
	jr	loop

init:
	ld	a, 0c9h
	ld	(044F9h), a
	ld	(05348h), a

	; Regist entry
	ld	a, 0c3h
	ld	(0FD9Fh), a
	ld	hl, 044F9h
	ld	(0FDA0h), hl
	ret

load_drv:
	di
	out	(03h),a

	ld	hl,09800h
	ld	de,04000h
	ld	bc,03E00h
	ldir

	ei

	in	a, (07h)
	cp	00
	jr	z, dev_psg
	cp	02
	jr	z, dev_msxa
	ld	a, 0c0h
	jr	init_end
dev_msxa:
	ld	a, 0e0h
	jr	init_end
dev_psg:
	xor	a
init_end:
	call	05278h		; Init
	ret

loaded:
	db	0FFh
